syntax = "proto3";

package vm_manager;

service VMManager {
  rpc PickNode     (PickNodeRequest)    returns (NodeInfo);
  rpc CreateVM     (CreateVMRequest)    returns (VMResponse);
  rpc StartVM      (VMRequest)          returns (VMResponse);
  rpc StopVM       (VMRequest)          returns (VMResponse);
  rpc RestartVM    (VMRequest)          returns (VMResponse);
  rpc GetVM        (VMRequest)          returns (VMResponse);
  rpc GetVMConsole (VMRequest)          returns (ConsoleResponse);
  rpc DeleteVM     (VMRequest)          returns (VMResponse);
  rpc ReinstallVM  (ReinstallVMRequest) returns (VMResponse);
}

message NodeInfo {
  int64  node_id   = 1;
  string ip        = 2;
  int32  grpc_port = 3;
}

message PickNodeRequest {
  repeated NodeInfo nodes = 1;
}

message CreateVMRequest {
  string          vm_name     = 1;
  int32           ram_mb      = 2;
  int32           vcpus       = 3;
  int32           disk_gb     = 4;
  string          base_image  = 5;
  NodeInfo        node        = 6;
  string          ip_address  = 7;
  string          vm_password = 8;
  optional string ssh_key     = 9;
}

message ReinstallVMRequest {
  string          uuid        = 1;
  NodeInfo        node        = 2;
  string          base_image  = 3;
  string          ip_address  = 4;
  string          vm_password = 5;
  optional string ssh_key     = 6;
}

message VMRequest {
  string   uuid = 1;
  NodeInfo node = 2;
}

message DiskStats {
  double read_mb_s  = 1;
  double write_mb_s = 2;
  double read_iops  = 3;
  double write_iops = 4;
}

message VMResponse {
  string             vm_name          = 1;
  string             uuid             = 2;
  string             status           = 3;
  double             cpu_percent      = 4;
  double             mem_total_mb     = 5;
  double             mem_used_mb      = 6;
  double             mem_available_mb = 7;
  optional DiskStats disk             = 8;
}

message ConsoleResponse {
  string host = 1;
  int32  port = 2;
}
