cookie:
  secure: false

logging:
  level:
    dev.nelit: DEBUG
    org.springframework.web: DEBUG
    com.fasterxml.jackson: DEBUG

spring:
  web:
    error:
      include-message: always
      include-binding-errors: always

scalar:
  enabled: true

pki:
  api-cert: C:/hosting/certs/api/tls.crt
  api-key: C:/hosting/certs/api/tls.key
  ca-cert: C:/hosting/certs/ca.crt
  ca-key: C:/hosting/certs/ca.key
