server:
  port: 4000

logging:
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30


spring:
  profiles:
    active: dev

  security:
    user:
      password: ignored

  application:
    name: hosting-api

  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: UTC

  sql:
    init:
      mode: always

  r2dbc:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expiration-days: ${JWT_EXPIRATION_DAYS}

grpc:
  vm-manager:
    host: ${GRPC_VM_MANAGER_HOST}
    port: ${GRPC_VM_MANAGER_PORT}

payments:
  stripe:
    secret-key: ${PAYMENTS_STRIPE_SECRET_KEY}
    webhook-secret: ${PAYMENTS_STRIPE_WEBHOOK_SECRET}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

scalar:
  enabled: false
