cookie:
  secure: false

logging:
  level:
    dev.nelit: DEBUG
    org.springframework.web: DEBUG
    com.fasterxml.jackson: DEBUG

spring:
  web:
    error:
      include-message: always
      include-binding-errors: always

scalar:
  enabled: true

pki:
  api-cert: ${PKI_API_CERT}
  api-key: ${PKI_API_KEY}
  ca-cert: ${PKI_CA_CERT}
  ca-key: ${PKI_CA_KEY}
