server:
  port: 4000

spring:
  security:
    user:
      password: ignored

  application:
    name: hosting-api

  jackson:
    property-naming-strategy: SNAKE_CASE

  sql:
    init:
      mode: always

  r2dbc:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expiration-days: ${JWT_EXPIRATION_DAYS}

grpc:
  vm-manager:
    host: ${GRPC_VM_MANAGER_HOST}
    port: ${GRPC_VM_MANAGER_PORT}