package dev.nelit.api.enums;

public enum AdminPermission {
    ADMIN_VIEW, ADMIN_MANAGE,
    NODE_VIEW, NODE_MANAGE,
    PLAN_MANAGE,
    IP_VIEW, IP_MANAGE,
    OS_IMAGE_VIEW, IS_IMAGE_MANAGE,
    PROMO_CODE_VIEW, PROMO_CODE_MANAGE,
    VM_VIEW, VM_MANAGE, VM_LIFECYCLE_MANAGE,
}
